name: Matrix Build Example

on:
  push:
    branches:
      - main

jobs:
  build-windows-2019:
    runs-on: windows-2019
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python and Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: python -m unittest discover
      working-directory: ./  # Current directory is the root of the repository
